// Mock rewards shaped like ScratchCardUiInfo (rewards/models/ui/ScratchCardUiInfo.kt),
// which RewardsMapper builds from GET /rewards (PaginatedRewardsResponse).
// Status is derived exactly as getScratchCardUiInfoStatus() does:
//   isLocked -> LOCKED, !isScratched -> UNSCRATCHED, isDisabled -> DISABLED, else REVEALED.

export const RewardStatus = { UNREVEALED: 'UNREVEALED', CREDITED: 'CREDITED', AVAILED: 'AVAILED', EXPIRED: 'EXPIRED' };
export const RewardType = {
  JUMBO_CASH: 'JUMBO_CASH',
  JUMBO_COINS: 'JUMBO_COINS',
  FREE_DELIVERY: 'FREE_DELIVERY',
  BETTER_LUCK_NEXT_TIME: 'BETTER_LUCK_NEXT_TIME',
  CART_OFFER: 'CART_OFFER',
};

export const REWARDS = [
  {
    scratchCardId: 'SC-90001',
    rewardId: 'RW-90001',
    isLocked: false,
    isDisabled: false,
    isScratched: false,
    rewardStatus: RewardStatus.UNREVEALED,
    rewardType: RewardType.JUMBO_COINS,
    rewardValue: 25,
    isRewardGold: false,
    image: '',
    title: '25 Jumbocoins',
    subTitle: 'Added to your SuperClub balance',
    showExpiry: true,
    validity: 0,
    nextCtaPresent: true,
    nextCtaLabel: 'CONTINUE SHOPPING',
    nextCtaLink: 'jumbotail://home',
    statusLabel: '',
    statusLabelColor: '#58a159',
    statusLabelBg: '#f2f8f2',
    detailsCompanyLogo: '',
    showDetailsCompanyLogo: true,
    detailsCompanyTitle: 'Jumbotail',
    detailsTitle: 'Congrats! You have won 25 Jumbocoins',
    detailsSubtitle: 'Jumbocoins have been added to your SuperClub balance',
    applicabilityLabel: 'Applicable on',
    applicabilityValue: 'SuperClub rewards catalogue',
    addedOn: '18 Aug 2026',
    detailsStartDate: '18 Aug 2026',
    detailsEndDate: '',
    detailsUsedOn: '',
    rewardSeeDetailsLabel: '',
    rewardSeeDetailsLink: '',
  },
  {
    scratchCardId: 'SC-90002',
    rewardId: 'RW-90002',
    isLocked: false,
    isDisabled: false,
    isScratched: true,
    rewardStatus: RewardStatus.CREDITED,
    rewardType: RewardType.JUMBO_CASH,
    rewardValue: 50,
    isRewardGold: true,
    image: '',
    title: '₹50 Jumbocash',
    subTitle: 'Credited to your account',
    showExpiry: true,
    validity: 0,
    nextCtaPresent: true,
    nextCtaLabel: 'START SHOPPING',
    nextCtaLink: 'jumbotail://home',
    statusLabel: '',
    statusLabelColor: '#58a159',
    statusLabelBg: '#f2f8f2',
    detailsCompanyLogo: '',
    showDetailsCompanyLogo: true,
    detailsCompanyTitle: 'Jumbotail',
    detailsTitle: 'Congrats! You have won ₹50 Jumbocash',
    detailsSubtitle: 'Jumbocash is credited to your account',
    applicabilityLabel: 'Applicable on',
    applicabilityValue: 'All orders',
    addedOn: '12 Aug 2026',
    detailsStartDate: '12 Aug 2026',
    detailsEndDate: '',
    detailsUsedOn: '',
    rewardSeeDetailsLabel: '',
    rewardSeeDetailsLink: '',
  },
  {
    scratchCardId: 'SC-90003',
    rewardId: 'RW-90003',
    isLocked: false,
    isDisabled: false,
    isScratched: true,
    rewardStatus: RewardStatus.CREDITED,
    rewardType: RewardType.FREE_DELIVERY,
    rewardValue: 1,
    isRewardGold: false,
    image: '',
    title: 'Free Delivery',
    subTitle: 'on your next order',
    showExpiry: true,
    validity: Date.UTC(2026, 8, 4),
    nextCtaPresent: true,
    nextCtaLabel: 'START SHOPPING',
    nextCtaLink: 'jumbotail://home',
    statusLabel: '',
    statusLabelColor: '#58a159',
    statusLabelBg: '#f2f8f2',
    detailsCompanyLogo: '',
    showDetailsCompanyLogo: true,
    detailsCompanyTitle: 'Jumbotail',
    detailsTitle: 'Congrats! You have won Free Delivery',
    detailsSubtitle: 'Applied automatically on your next order',
    applicabilityLabel: 'Applicable on',
    applicabilityValue: 'Next order',
    addedOn: '10 Aug 2026',
    detailsStartDate: '10 Aug 2026',
    detailsEndDate: '4 Sep 2026',
    detailsUsedOn: '',
    rewardSeeDetailsLabel: '',
    rewardSeeDetailsLink: '',
  },
  {
    scratchCardId: 'SC-90004',
    rewardId: 'RW-90004',
    isLocked: false,
    isDisabled: true,
    isScratched: true,
    rewardStatus: RewardStatus.EXPIRED,
    rewardType: RewardType.CART_OFFER,
    rewardValue: 100,
    isRewardGold: false,
    image: '',
    title: '₹100 off above ₹5,000',
    subTitle: 'on staples',
    showExpiry: false,
    validity: Date.UTC(2026, 6, 31),
    nextCtaPresent: false,
    nextCtaLabel: '',
    nextCtaLink: '',
    statusLabel: 'Expired',
    statusLabelColor: '#58a159',
    statusLabelBg: '#C4E9C9',
    detailsCompanyLogo: '',
    showDetailsCompanyLogo: true,
    detailsCompanyTitle: 'Jumbotail',
    detailsTitle: 'This offer has expired',
    detailsSubtitle: 'The reward was not used before the end date',
    applicabilityLabel: 'Applicable on',
    applicabilityValue: 'Staples',
    addedOn: '1 Jul 2026',
    detailsStartDate: '1 Jul 2026',
    detailsEndDate: '31 Jul 2026',
    detailsUsedOn: '',
    rewardSeeDetailsLabel: '',
    rewardSeeDetailsLink: '',
  },
  {
    scratchCardId: 'SC-90005',
    rewardId: 'RW-90005',
    isLocked: false,
    isDisabled: true,
    isScratched: true,
    rewardStatus: RewardStatus.AVAILED,
    rewardType: RewardType.CART_OFFER,
    rewardValue: 75,
    isRewardGold: false,
    image: '',
    title: '₹75 off above ₹3,000',
    subTitle: 'on beverages',
    showExpiry: false,
    validity: Date.UTC(2026, 6, 20),
    nextCtaPresent: false,
    nextCtaLabel: '',
    nextCtaLink: '',
    statusLabel: 'Used',
    statusLabelColor: '#58a159',
    statusLabelBg: '#C4E9C9',
    detailsCompanyLogo: '',
    showDetailsCompanyLogo: true,
    detailsCompanyTitle: 'Jumbotail',
    detailsTitle: 'You used this reward',
    detailsSubtitle: 'Applied on order JT-88213',
    applicabilityLabel: 'Applicable on',
    applicabilityValue: 'Beverages',
    addedOn: '2 Jul 2026',
    detailsStartDate: '2 Jul 2026',
    detailsEndDate: '20 Jul 2026',
    detailsUsedOn: '14 Jul 2026',
    rewardSeeDetailsLabel: 'View order',
    rewardSeeDetailsLink: 'jumbotail://orders',
  },
  {
    scratchCardId: 'SC-90006',
    rewardId: 'RW-90006',
    isLocked: true,
    isDisabled: false,
    isScratched: false,
    rewardStatus: RewardStatus.UNREVEALED,
    rewardType: RewardType.BETTER_LUCK_NEXT_TIME,
    rewardValue: 0,
    isRewardGold: false,
    image: '',
    title: '',
    subTitle: '',
    showExpiry: false,
    validity: 0,
    nextCtaPresent: false,
    nextCtaLabel: '',
    nextCtaLink: '',
    statusLabel: '',
    statusLabelColor: '#58a159',
    statusLabelBg: '#f2f8f2',
    detailsCompanyLogo: '',
    showDetailsCompanyLogo: true,
    detailsCompanyTitle: 'Jumbotail',
    detailsTitle: 'Place an order to unlock this scratch card',
    detailsSubtitle: '',
    applicabilityLabel: '',
    applicabilityValue: '',
    addedOn: '',
    detailsStartDate: '',
    detailsEndDate: '',
    detailsUsedOn: '',
    rewardSeeDetailsLabel: '',
    rewardSeeDetailsLink: '',
  },
];

// getScratchCardUiInfoStatus()
export function cardStatus(c) {
  if (c.isLocked) return 'LOCKED';
  if (!c.isScratched) return 'UNSCRATCHED';
  if (c.isDisabled) return 'DISABLED';
  return 'REVEALED';
}

// getRewardExpiry(): JUMBO_CASH / JUMBO_COINS never expire, otherwise
// RewardTimeUtil.getUseBeforeExpiryTimeStr(validity)
const NOW = Date.UTC(2026, 7, 20);
export function rewardExpiry(c) {
  if (c.rewardType === RewardType.JUMBO_CASH || c.rewardType === RewardType.JUMBO_COINS) {
    return 'Never expires';
  }
  const days = Math.max(0, Math.ceil((c.validity - NOW) / 86400000));
  return `${days} days left`;
}

export function markScratched(scratchCardId) {
  const c = REWARDS.find((r) => r.scratchCardId === scratchCardId);
  if (!c) return;
  c.isScratched = true;
  if (c.rewardStatus === RewardStatus.UNREVEALED) c.rewardStatus = RewardStatus.CREDITED;
}

export function getReward(scratchCardId) {
  return REWARDS.find((r) => r.scratchCardId === scratchCardId);
}
