// UI strings for the scheme page, both languages. Product and brand names stay
// Latin. The big amount renders from parts (prefix, amount, suffix) so the number
// can be set larger than the words around it in both languages.
//
// The audience is Hindi-first. The app picks the language from the account
// setting; the prototype renders English and T.hi proves the layout survives.
export const T = {
  en: {
    startsLine: (d) => `Starts ${d}`,
    endsLine: (d) => `Ends ${d} • `,
    daysLeft: (days) => `${days} days left`,
    endedLine: (d) => `Ended ${d}`,
    youWon: 'YOU WON',
    qualified: 'QUALIFIED',
    nextGift: 'NEXT GIFT',
    topGift: 'TOP GIFT',
    wonTop: 'YOU WON THE TOP GIFT',
    // The top target crossed while the scheme still runs: reached, not yet won.
    topReached: 'TOP GIFT REACHED',
    topCashReached: 'TOP CASHBACK REACHED',
    reachedHeadline: (short) => `You've qualified for the ${short}`,
    reachedHeadlineCash: (amount) => `You've qualified for ${amount} cashback`,
    reachedNote: (d) => `Confirmed when the scheme ends on ${d}`,
    targetReached: 'Target reached',
    footReached: (short) => `You've qualified for the ${short}`,
    footReachedCash: (amount) => `You've qualified for ${amount} cashback`,
    // A scheme that pays no product pays cashback (as JumboCash), and says so.
    nextCash: 'NEXT CASHBACK',
    topCash: 'TOP CASHBACK',
    wonTopCash: 'YOU WON THE TOP CASHBACK',
    cashList: 'CASHBACK',
    wonHeadlineCash: (short) => `You won ${short}`,
    cardCash: (amount) => `${amount} cashback`,
    cardCashMany: (n) => `cashback at ${n} targets`,
    securedRow: (name) => `You've qualified for the ${name}`,
    qualifiedAt: (at) => `Qualified at ${at}`,
    cashbackWord: 'cashback',
    morePrefix: 'Buy ', moreSuffix: ' more',
    onlyPrefix: 'Buy just ', onlySuffix: ' more',
    rest: (next) => `to win the ${next}`,
    finalBought: (amt) => `Final buying: ${amt}`,
    cta: () => 'Buy Eligible Products',
    ctaEnded: 'See running schemes',
    startsNote: (d) => `Starts ${d}. Buy eligible products to win.`,
    topNote: (d) => `Nothing is left to win. We order your gift after ${d}.`,
    missedTitle: 'Scheme ended',
    missedNote: 'You did not reach the first target.',
    pendingNote: 'We place your Amazon order in a few days.',
    orderedNote: (by) => `On the way to your shop. Arrives by ${by}.`,
    deliveredNote: (d) => `Delivered to your shop on ${d}.`,
    giftList: 'GIFT LIST',
    rulesTitle: 'ELIGIBILITY',
    rulesCounts: 'Counts toward your target',
    rulesMore: (n) => `See ${n} more`,
    rulesCardIn: 'Eligible products',
    rulesCardOut: 'Non eligible products',
    rulesViewMore: (n) => `View ${n} more`,
    rulesViewLess: 'View less',
    rulesLess: 'See less',
    rulesNotCounts: "Doesn't count toward your target",
    sellersTitle: 'ELIGIBLE SELLER',
    sellersCounts: 'Only purchases from this seller count',
    sellerFrom: (city) => `Ships from ${city}`,
    termsTitle: 'TERMS AND CONDITIONS',
    ordersTitle: (n) => (n === 1 ? '1 eligible purchase made' : `${n} eligible purchases made`),
    ordersKnowMore: 'Know more',
    eligible: 'Eligible',
    notEligible: 'Not eligible',
    next: 'NEXT',
    steps: ['Won', 'Ordered', 'On the way', 'Delivered'],
    shipsHere: 'Your gift ships here',
    confirm: 'Confirm address',
    change: 'Change',
    confirmed: 'Address confirmed',
    facts: (deliverBy, window, ended) => [
      ['calendar', `Scheme window: ${window}`],
      ...(ended ? [] : [['truck', `Amazon delivers to your shop by ${deliverBy}`]]),
    ],
    targetWord: 'Target',
    stampWon: 'WON',
    stampOnTheWay: 'ON THE WAY',
    stampDelivered: 'DELIVERED',
    stampMissed: 'MISSED',
    wonHeadline: (short) => `You won the ${short}`,
    wonStatusDelivered: (d) => `Delivered to your shop, ${d}`,
    wonStatusOnTheWay: (by) => `On the way. Arrives by ${by}`,
    wonStatusPending: 'Your gift is being confirmed',
    wonStatusTop: (d) => `The top gift. We order it after ${d}`,
    running: 'RUNNING',
    completed: 'COMPLETED',
    emptyTitle: 'No schemes right now',
    emptyLine: 'New schemes will show here.',
    emptyDoneTitle: 'Nothing completed yet',
    emptyDoneLine: 'Finished schemes will show here.',
    // The card footer: the targets, in the app's own word, and what they pay.
    cardTargets: (lo, hi, n, reward) => (n === 1 ? `Target ${lo} · ${reward || '1 gift'}` : `Targets ${lo} to ${hi} · ${reward || `${n} gifts`}`),
    cardWon: (at) => `Won at the ${at} target`,
    // The card footer: the gifts, not the targets (the bar shows the target).
    footWon: (short) => `You won the ${short}`,
    footWonCash: (amount) => `You won ${amount} cashback`,
    footMissed: 'No gift this time',
    footMissedCash: 'No cashback this time',
    footUpTo: (n, short) => `${n} slabs · Top gift: ${short}`,
    footCashUpTo: (n, amount) => `${n} slabs · Up to ${amount} cashback`,
    footWinOne: (short) => `Win the ${short}`,
    footCashOne: (amount) => `Win ${amount} cashback`,
    cardMissed: 'No target reached',
    cardStarts: (d, n, reward) => `Starts ${d} · ${reward || (n === 1 ? '1 gift' : `${n} gifts`)}`,
  },
  hi: {
    startsLine: (d) => `${d} से शुरू`,
    endsLine: (d) => `${d} तक • `,
    daysLeft: (days) => `${days} दिन बाक़ी`,
    endedLine: (d) => `${d} को ख़त्म`,
    youWon: 'आपने जीता',
    qualified: 'क्वालिफ़ाइड',
    nextGift: 'अगला गिफ़्ट',
    topGift: 'टॉप गिफ़्ट',
    wonTop: 'आपने टॉप गिफ़्ट जीता',
    topReached: 'टॉप गिफ़्ट तक पहुँचे',
    topCashReached: 'टॉप कैशबैक तक पहुँचे',
    reachedHeadline: (short) => `आपने ${short} के लिए क्वालिफ़ाई किया`,
    reachedHeadlineCash: (amount) => `आपने ${amount} कैशबैक के लिए क्वालिफ़ाई किया`,
    reachedNote: (d) => `${d} को स्कीम ख़त्म होने पर कन्फ़र्म`,
    targetReached: 'टारगेट पूरा',
    footReached: (short) => `आपने ${short} के लिए क्वालिफ़ाई किया`,
    footReachedCash: (amount) => `आपने ${amount} कैशबैक के लिए क्वालिफ़ाई किया`,
    nextCash: 'अगला कैशबैक',
    topCash: 'टॉप कैशबैक',
    wonTopCash: 'आपने टॉप कैशबैक जीता',
    cashList: 'कैशबैक',
    wonHeadlineCash: (short) => `आपने ${short} जीता`,
    cardCash: (amount) => `${amount} कैशबैक`,
    cardCashMany: (n) => `${n} टारगेट पर कैशबैक`,
    securedRow: (name) => `आपने ${name} के लिए क्वालिफ़ाई किया`,
    qualifiedAt: (at) => `${at} पर क्वालिफ़ाइड`,
    cashbackWord: 'कैशबैक',
    morePrefix: '', moreSuffix: ' और ख़रीदें',
    onlyPrefix: 'बस ', onlySuffix: ' और ख़रीदें',
    rest: (next) => `और ${next} जीतें`,
    finalBought: (amt) => `कुल ख़रीदारी: ${amt}`,
    cta: () => 'एलिजिबल प्रोडक्ट ख़रीदें',
    ctaEnded: 'चल रही स्कीमें देखें',
    startsNote: (d) => `${d} से शुरू। जीतने के लिए एलिजिबल प्रोडक्ट ख़रीदें।`,
    topNote: (d) => `जीतने को और कुछ नहीं बचा। ${d} के बाद हम आपका ऑर्डर करेंगे।`,
    missedTitle: 'स्कीम ख़त्म',
    missedNote: 'पहला टारगेट पूरा नहीं हुआ।',
    pendingNote: 'कुछ दिनों में हम आपका Amazon ऑर्डर करेंगे।',
    orderedNote: (by) => `आपकी दुकान की ओर रवाना। ${by} तक पहुँचेगा।`,
    deliveredNote: (d) => `${d} को आपकी दुकान पर डिलीवर हुआ।`,
    giftList: 'गिफ़्ट लिस्ट',
    rulesTitle: 'एलिजिबिलिटी',
    rulesCounts: 'आपके टारगेट में गिना जाता है',
    rulesMore: (n) => `${n} और देखें`,
    rulesCardIn: 'एलिजिबल प्रोडक्ट',
    rulesCardOut: 'नॉन-एलिजिबल प्रोडक्ट',
    rulesViewMore: (n) => `${n} और देखें`,
    rulesViewLess: 'कम देखें',
    rulesLess: 'कम देखें',
    rulesNotCounts: 'आपके टारगेट में नहीं गिना जाता',
    sellersTitle: 'एलिजिबल सेलर',
    sellersCounts: 'सिर्फ़ इस सेलर से ख़रीद गिनी जाती है',
    sellerFrom: (city) => `${city} से शिपिंग`,
    termsTitle: 'नियम और शर्तें',
    ordersTitle: (n) => `${n} एलिजिबल ख़रीद की गई`,
    ordersKnowMore: 'और जानें',
    eligible: 'एलिजिबल',
    notEligible: 'एलिजिबल नहीं',
    next: 'अगला',
    steps: ['जीता', 'ऑर्डर हुआ', 'रास्ते में', 'डिलीवर'],
    shipsHere: 'आपका गिफ़्ट यहाँ आएगा',
    confirm: 'पता सही है',
    change: 'बदलें',
    confirmed: 'पता कन्फ़र्म हो गया',
    facts: (deliverBy, window, ended) => [
      ['calendar', `स्कीम की अवधि: ${window}`],
      ...(ended ? [] : [['truck', `Amazon से डिलीवरी, ${deliverBy} तक`]]),
    ],
    targetWord: 'टारगेट',
    stampWon: 'जीता',
    stampOnTheWay: 'रास्ते में',
    stampDelivered: 'डिलीवर',
    stampMissed: 'छूट गया',
    wonHeadline: (short) => `आपने ${short} जीता`,
    wonStatusDelivered: (d) => `${d} को आपकी दुकान पर डिलीवर हुआ`,
    wonStatusOnTheWay: (by) => `रास्ते में। ${by} तक पहुँचेगा`,
    wonStatusPending: 'आपका गिफ़्ट कन्फ़र्म हो रहा है',
    wonStatusTop: (d) => `टॉप गिफ़्ट। ${d} के बाद हम ऑर्डर करेंगे`,
    running: 'चल रही',
    completed: 'पूरी हुई',
    emptyTitle: 'अभी कोई स्कीम नहीं',
    emptyLine: 'नई स्कीमें यहाँ दिखेंगी।',
    emptyDoneTitle: 'अभी कोई पूरी नहीं हुई',
    emptyDoneLine: 'ख़त्म हुई स्कीमें यहाँ दिखेंगी।',
    cardTargets: (lo, hi, n, reward) => (n === 1 ? `टारगेट ${lo} · ${reward || '1 गिफ्ट'}` : `टारगेट ${lo} से ${hi} · ${reward || `${n} गिफ्ट`}`),
    cardWon: (at) => `${at} टारगेट पर जीता`,
    footWon: (short) => `आपने ${short} जीता`,
    footWonCash: (amount) => `आपने ${amount} कैशबैक जीता`,
    footMissed: 'इस बार कोई गिफ्ट नहीं',
    footMissedCash: 'इस बार कोई कैशबैक नहीं',
    footUpTo: (n, short) => `${n} स्लैब · टॉप गिफ्ट: ${short}`,
    footCashUpTo: (n, amount) => `${n} स्लैब · ${amount} तक कैशबैक`,
    footWinOne: (short) => `${short} जीतें`,
    footCashOne: (amount) => `${amount} कैशबैक जीतें`,
    cardMissed: 'कोई टारगेट पूरा नहीं हुआ',
    cardStarts: (d, n, reward) => `${d} से शुरू · ${reward || `${n} गिफ्ट`}`,
  },
};
