// UI strings for the scheme page, both languages. Product and brand names stay
// Latin. The big amount renders from parts (prefix, amount, suffix) so the number
// can be set larger than the words around it in both languages.
//
// The audience is Hindi-first. The app picks the language from the account
// setting; the prototype renders English and T.hi proves the layout survives.
export const T = {
  en: {
    startsLine: (d) => `Starts ${d}`,
    endsLine: (d) => `Ends ${d} • `,
    daysLeft: (days) => `${days} days left`,
    endedLine: (d) => `Ended ${d}`,
    youWon: 'YOU WON',
    qualified: 'QUALIFIED',
    nextGift: 'NEXT GIFT',
    topGift: 'TOP GIFT',
    wonTop: 'YOU WON THE TOP GIFT',
    // A scheme that pays no product pays cashback (as JumboCash), and says so.
    nextCash: 'NEXT CASHBACK',
    topCash: 'TOP CASHBACK',
    wonTopCash: 'YOU WON THE TOP CASHBACK',
    cashList: 'CASHBACK',
    wonHeadlineCash: (short) => `You won ${short}`,
    cardCash: (amount) => `${amount} cashback`,
    cardCashMany: (n) => `cashback at ${n} targets`,
    securedRow: (name) => `You've qualified for the ${name}`,
    qualifiedWord: 'qualified',
    morePrefix: 'Buy ', moreSuffix: ' more',
    onlyPrefix: 'Buy just ', onlySuffix: ' more',
    rest: (next) => `to win the ${next}`,
    finalBought: (amt) => `Final buying: ${amt}`,
    cta: () => 'View Eligible Products',
    ctaEnded: 'See running schemes',
    startsNote: (d) => `Buy eligible products from ${d}. The highest slab you cross is your gift.`,
    topNote: (d) => `Nothing is left to win. We order your gift after ${d}.`,
    missedTitle: 'The scheme ended',
    missedNote: 'No slab was crossed this time. Your running schemes are in the Running tab.',
    pendingNote: 'We place your Amazon order in a few days.',
    orderedNote: (by) => `On the way to your shop. Arrives by ${by}.`,
    deliveredNote: (d) => `Delivered to your shop on ${d}.`,
    giftList: 'GIFT LIST',
    rulesTitle: 'ELIGIBLE PRODUCTS',
    rulesDesc: 'Following company/brand/category/products are eligible',
    eligible: 'Eligible',
    notEligible: 'Not eligible',
    next: 'NEXT',
    steps: ['Won', 'Ordered', 'On the way', 'Delivered'],
    shipsHere: 'Your gift ships here',
    confirm: 'Confirm address',
    change: 'Change',
    confirmed: 'Address confirmed',
    facts: (deliverBy, window, ended) => [
      ['calendar', `Scheme window: ${window}`],
      ['gift', 'One gift per shop: the highest slab you cross'],
      ...(ended ? [] : [['truck', `Amazon delivers to your shop by ${deliverBy}`]]),
    ],
    targetWord: 'Target',
    stampWon: 'WON',
    stampOnTheWay: 'ON THE WAY',
    stampDelivered: 'DELIVERED',
    wonHeadline: (short) => `You won the ${short}`,
    wonStatusDelivered: (d) => `Delivered to your shop, ${d}`,
    wonStatusOnTheWay: (by) => `On the way. Arrives by ${by}`,
    wonStatusPending: 'Your gift is being confirmed',
    wonStatusTop: (d) => `The top gift. We order it after ${d}`,
    running: 'RUNNING',
    completed: 'COMPLETED',
    emptyTitle: 'No schemes yet',
    emptyLine: 'When a scheme starts for your shop, it shows here.',
    emptyDoneTitle: 'No completed schemes',
    emptyDoneLine: 'A scheme moves here when its window ends.',
    // The card footer: the targets, in the app's own word, and what they pay.
    cardTargets: (lo, hi, n, reward) => (n === 1 ? `Target ${lo} · ${reward || '1 gift'}` : `Targets ${lo} to ${hi} · ${reward || `${n} gifts`}`),
    cardWon: (at) => `Won at the ${at} target`,
    // The card footer: the gifts, not the targets (the bar shows the target).
    footGifts: (n) => (n === 1 ? '1 gift to win' : `${n} gifts to win`),
    footCash: (n, amount) => (n === 1 ? `${amount} cashback to win` : `Cashback at ${n} targets`),
    footWon: (short) => `Won the ${short}`,
    footWonCash: (amount) => `Won ${amount} cashback`,
    footMissed: 'No gift won',
    footMissedCash: 'No cashback won',
    footUpTo: (n, short) => `${n} gifts, up to the ${short}`,
    footCashUpTo: (n, amount) => `Cashback at ${n} targets, up to ${amount}`,
    footWinOne: (short) => `Win the ${short}`,
    footCashOne: (amount) => `Win ${amount} cashback`,
    cardMissed: 'No target reached',
    cardStarts: (d, n, reward) => `Starts ${d} · ${reward || (n === 1 ? '1 gift' : `${n} gifts`)}`,
  },
  hi: {
    startsLine: (d) => `${d} से शुरू`,
    endsLine: (d) => `${d} तक • `,
    daysLeft: (days) => `${days} दिन बाक़ी`,
    endedLine: (d) => `${d} को ख़त्म`,
    youWon: 'आपने जीता',
    qualified: 'क्वालिफ़ाइड',
    nextGift: 'अगला गिफ़्ट',
    topGift: 'टॉप गिफ़्ट',
    wonTop: 'आपने टॉप गिफ़्ट जीता',
    nextCash: 'अगला कैशबैक',
    topCash: 'टॉप कैशबैक',
    wonTopCash: 'आपने टॉप कैशबैक जीता',
    cashList: 'कैशबैक',
    wonHeadlineCash: (short) => `आपने ${short} जीता`,
    cardCash: (amount) => `${amount} कैशबैक`,
    cardCashMany: (n) => `${n} टारगेट पर कैशबैक`,
    securedRow: (name) => `आपने ${name} के लिए क्वालिफ़ाई किया`,
    qualifiedWord: 'क्वालिफ़ाइड',
    morePrefix: '', moreSuffix: ' और ख़रीदें',
    onlyPrefix: 'बस ', onlySuffix: ' और ख़रीदें',
    rest: (next) => `और ${next} जीतें`,
    finalBought: (amt) => `कुल ख़रीदारी: ${amt}`,
    cta: () => 'एलिजिबल प्रोडक्ट देखें',
    ctaEnded: 'चल रही स्कीमें देखें',
    startsNote: (d) => `${d} से एलिजिबल प्रोडक्ट ख़रीदें। जो सबसे ऊँचा स्लैब पार करें, वही गिफ़्ट आपका।`,
    topNote: (d) => `जीतने को और कुछ नहीं बचा। ${d} के बाद हम आपका ऑर्डर करेंगे।`,
    missedTitle: 'स्कीम ख़त्म हो गई',
    missedNote: 'इस बार कोई स्लैब पार नहीं हुआ। चल रही स्कीमें "चल रही" टैब में हैं।',
    pendingNote: 'कुछ दिनों में हम आपका Amazon ऑर्डर करेंगे।',
    orderedNote: (by) => `आपकी दुकान की ओर रवाना। ${by} तक पहुँचेगा।`,
    deliveredNote: (d) => `${d} को आपकी दुकान पर डिलीवर हुआ।`,
    giftList: 'गिफ़्ट लिस्ट',
    rulesTitle: 'एलिजिबल प्रोडक्ट',
    rulesDesc: 'ये कंपनी/ब्रांड/कैटेगरी/प्रोडक्ट एलिजिबल हैं',
    eligible: 'एलिजिबल',
    notEligible: 'एलिजिबल नहीं',
    next: 'अगला',
    steps: ['जीता', 'ऑर्डर हुआ', 'रास्ते में', 'डिलीवर'],
    shipsHere: 'आपका गिफ़्ट यहाँ आएगा',
    confirm: 'पता सही है',
    change: 'बदलें',
    confirmed: 'पता कन्फ़र्म हो गया',
    facts: (deliverBy, window, ended) => [
      ['calendar', `स्कीम की अवधि: ${window}`],
      ['gift', '1 दुकान, 1 गिफ़्ट: जो सबसे ऊँचा स्लैब पार करें'],
      ...(ended ? [] : [['truck', `Amazon से डिलीवरी, ${deliverBy} तक`]]),
    ],
    targetWord: 'टारगेट',
    stampWon: 'जीता',
    stampOnTheWay: 'रास्ते में',
    stampDelivered: 'डिलीवर',
    wonHeadline: (short) => `आपने ${short} जीता`,
    wonStatusDelivered: (d) => `${d} को आपकी दुकान पर डिलीवर हुआ`,
    wonStatusOnTheWay: (by) => `रास्ते में। ${by} तक पहुँचेगा`,
    wonStatusPending: 'आपका गिफ़्ट कन्फ़र्म हो रहा है',
    wonStatusTop: (d) => `टॉप गिफ़्ट। ${d} के बाद हम ऑर्डर करेंगे`,
    running: 'चल रही',
    completed: 'पूरी हुई',
    emptyTitle: 'अभी कोई स्कीम नहीं',
    emptyLine: 'जब आपकी दुकान के लिए स्कीम शुरू होगी, यहाँ दिखेगी।',
    emptyDoneTitle: 'कोई पूरी हुई स्कीम नहीं',
    emptyDoneLine: 'स्कीम की अवधि खत्म होने पर वह यहाँ आती है।',
    cardTargets: (lo, hi, n, reward) => (n === 1 ? `टारगेट ${lo} · ${reward || '1 गिफ्ट'}` : `टारगेट ${lo} से ${hi} · ${reward || `${n} गिफ्ट`}`),
    cardWon: (at) => `${at} टारगेट पर जीता`,
    footGifts: (n) => `${n} गिफ्ट जीतने के लिए`,
    footCash: (n, amount) => (n === 1 ? `${amount} कैशबैक जीतने के लिए` : `${n} टारगेट पर कैशबैक`),
    footWon: (short) => `${short} जीता`,
    footWonCash: (amount) => `${amount} कैशबैक जीता`,
    footMissed: 'कोई गिफ्ट नहीं जीता',
    footMissedCash: 'कोई कैशबैक नहीं जीता',
    footUpTo: (n, short) => `${n} गिफ्ट, ${short} तक`,
    footCashUpTo: (n, amount) => `${n} टारगेट पर कैशबैक, ${amount} तक`,
    footWinOne: (short) => `${short} जीतें`,
    footCashOne: (amount) => `${amount} कैशबैक जीतें`,
    cardMissed: 'कोई टारगेट पूरा नहीं हुआ',
    cardStarts: (d, n, reward) => `${d} से शुरू · ${reward || `${n} गिफ्ट`}`,
  },
};
